### ISSUE TITLE
CephBase: scraping a ScratchPad

### ISSUE THREAD

**Issue by eliagbayani** [EOL/ContentImport#1]
Scraping a ScratchPad, http://cephbase.eol.org/

Hi, Eli!

I'm adding this to your queue, and tried to make a ticket for it, but JIRA is showing me errors today, so here's the description:

We are still somewhat hopeful that we'll be able to use the native Scratchpad export tools to connect our content partners inhabiting ScratchPads- however, a couple of them have run into a 
failure of the DwC-A file to manifest when we turned it on, and one of these partners is in a hurry. Meanwhile, I'm not sure at what level ScratchPads are being supported currently 
(I have reported a couple of problems without substantive response) so this is a method we may need to use again later. 

The target site is http://cephbase.eol.org/ . We would like to harvest the complete taxonomy (http://cephbase.eol.org/taxonomy/term/8), and all images (http://cephbase.eol.org/gallery) 
and references (http://cephbase.eol.org/biblio) that have something in the taxonomic name field. (There are lots of photos of people also, which can be excluded.) 
If it's practical to get the text also, (eg: first section of http://cephbase.eol.org/taxonomy/term/326/descriptions) go ahead, but if it gets messy, this can be neglected.

Let's assume the site itself won't disappear, and use their "Download the original" addresses (eg: http://cephbase.eol.org/sites/cephbase.eol.org/files/cb1072.jpg) as mediaURLs and 
their taxon page tabs (eg: http://cephbase.eol.org/taxonomy/term/845/media) as source links (unless you can detect something more specific. I don't think ScratchPads currently have urls for viewing a single image with attribution)

Please also include the metadata fields Description, Imaging technique (concatenate this with description, I think), Licence, and Creator. This will be a static resource, 
as I'll be contacting creators and negotiating licenses to update the resource file manually. If ScratchPads revives later, we may overwrite with something else. 

If I've forgotten anything, please let me know :)

Jen

**Comment by eliagbayani** [comment]
Hi @jhammock ,

First crack of the DwCA. [OpenData](https://opendata.eol.org/dataset/cephbase
).

Stats:
http://eol.org/schema/reference/reference --- Total = 9135
http://rs.tdwg.org/dwc/terms/taxon --- Total = 1623
http://eol.org/schema/agent/agent --- Total = 27

There are 1656 images but all have invalid licenses:
-- value => "http://creativecommons.org/licences/by-nc-nd/3.0/"
-- value => "all rights reserved"

**Comment by jhammock** [comment]
Perfect, thanks. This is a one time harvest, so I can update the licenses manually as we negotiate with the agents. This task is done.

**Comment by eliagbayani** [comment]
Text objects (associations) now included, with respective references. [OpenData](https://opendata.eol.org/dataset/cephbase).
http://rs.tdwg.org/ontology/voc/SPMInfoItems#Associations: 208

**Comment by jhammock** [comment]
Looks good, thanks!
