### ISSUE TITLE
Tweak to micro*scope

### ISSUE THREAD

**Issue by jhammock** [EOL/ContentImport#17]
Some of the [microscope](https://content.eol.org/resources/776) images belong to Wolfgang, and he has confirmed that they are redundant with images in protisten.de, where they are being kept up to date with IDs, etc. so he requests that we remove them from the microscope resource. They can be identified by this text in the description:

"Images were taken using Zeiss Universal with Olympus C7070 CCD camera"

@eliagbayani can you filter them out and queue up for reharvest, please?

**Comment by eliagbayani** [comment]
Hi Jen,
Connector created. DwCA updated.
[micro*scope](https://content.eol.org/resources/776) is now being harvested.
Thanks.

**Comment by eliagbayani** [comment]
Hi Jen,
micro*scope has been published.
https://eol.org/pages/491144/media?resource_id=681
Have asked Wolfgang to check as well.
Thanks.

**Comment by eliagbayani** [comment]
On Thu, Oct 3, 2024 at 2:13 PM Wolfgang Bettighofer <Wolfgang.Bettighofer@gmx.de> wrote:
Hi Eli,

thank you! I've checked some of my old erroneous ids in my micro*score set, they are no more visible in EOL.

Best
Wolfgang

**Comment by jhammock** [comment]
Nice work, Eli! Good to know we've got some solid ground under us with republishing, as well.
